const endpoint = {
  AUTH: "/auth",
  CATEGORY: "/category",
  CERTIFICATE: "/certification",
  COMPETENCY: "/competency",
  COMPLETED: "/completed",
  KAJIAN: "/kajian",
  KUIS_COMPETENCY: "/kuiscompetency",
  LKP: "/lkp",
  MEDIA: "/media",
  NOTIFICATION: "/notification",
  RESUME: "/resume",
  SAVE: "/save",
  SCORE: "/score",
  SCORE_SOP_IK: "/scoresopik",
  SCORE_SOP: "/scoresop",
  SCORE_IK: "/scoreik",
  SOP_IK: "/sopik",
  SOP: "/sop",
  IK: "/ik",
  KUIS_SOP: "/kuissop",
  KUIS_IK: "/kuisik",
  KUIS_SOP_IK: "/kuissopik",
  SUB_COMPETENCY: "/subcompetency",
  SUNNAH: "/sunnah",
  VIDEO: "/video",

};

export default endpoint;
